// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Algorithms Notes',
      link: {
        type: 'generated-index',
        description: 'CS4820 notes organized around the major algorithmic ideas covered so far.',
      },
      items: [
        'notes/stable-matching',
        'notes/greedy-algorithms',
        'notes/dynamic-programming',
        'notes/divide-and-conquer',
        'notes/np-completeness',
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus Tutorial',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
